name: recipe_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.2
  cupertino_icons: ^1.0.2
  unicons: ^2.0.2
  google_fonts: ^5.0.0
  cached_network_image: ^3.1.0+1
  sizer: ^2.0.15
  provider: ^6.0.1
  image_picker: ^1.1.2
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/recipebook.gif
      - assets/recipe_dataset/recipes.csv
      - assets/recipe_dataset/images/


