name: recipe_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.2
  cupertino_icons: ^1.0.2
  unicons: ^2.0.2
  google_fonts: ^5.0.0
  cached_network_image: ^3.2.3
  google_sign_in: ^5.4.0
  sizer: ^2.0.15
  provider: ^6.0.5
  image_picker: ^1.0.4
  http: ^1.3.0
  firebase_storage: ^12.4.5
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  flutter_localizations:
    sdk: flutter
  intl: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  path: ^1.8.3
  shared_preferences: ^2.2.0
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo_foreground.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/recipebook.gif
    - assets/recipe_dataset/recipes.csv
    - assets/recipe_dataset/images/
    - assets/google_icon.png
