// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2nVwSeCmZ1Gl8FOw7s7NBeOteKeM89I',
    appId: '1:1043018510793:android:3dda7c04ae594c55ca7818',
    messagingSenderId: '1043018510793',
    projectId: 'recipeapp-e8eae',
    storageBucket: 'recipeapp-e8eae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSC0lP3AejpASDKbzmgN2TDiU2DGVnoCk',
    appId: '1:1043018510793:ios:520ccb6127eb9977ca7818',
    messagingSenderId: '1043018510793',
    projectId: 'recipeapp-e8eae',
    storageBucket: 'recipeapp-e8eae.firebasestorage.app',
    iosClientId: '1043018510793-qmfbhiac744rfbsq803pucove0n2amb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSC0lP3AejpASDKbzmgN2TDiU2DGVnoCk',
    appId: '1:1043018510793:ios:520ccb6127eb9977ca7818',
    messagingSenderId: '1043018510793',
    projectId: 'recipeapp-e8eae',
    storageBucket: 'recipeapp-e8eae.firebasestorage.app',
    iosClientId: '1043018510793-qmfbhiac744rfbsq803pucove0n2amb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.recipeApp',
  );

}